-- lib.addCommand('garagesetting', {
--     help = 'Use this to set up a garage/job vehicle shop/police impound',
--     params = {
--         {
--             name = 'type',
--             type = 'string',
--             help = 'available types (garage/jobvehshop/policeimpound)',
--         },
--     },
--     restricted = 'group.admin'
-- }, function(source, args, raw)
    
-- end)